import Foundation

enum StyleAdaptationRules {
    // MARK: - Casual Contractions (expanded → contracted)

    static let casualContractions: [(expanded: String, contracted: String)] = [
        ("I am",        "I'm"),
        ("I have",      "I've"),
        ("I will",      "I'll"),
        ("I would",     "I'd"),
        ("you are",     "you're"),
        ("you have",    "you've"),
        ("you will",    "you'll"),
        ("you would",   "you'd"),
        ("he is",       "he's"),
        ("he has",      "he's"),
        ("he will",     "he'll"),
        ("he would",    "he'd"),
        ("she is",      "she's"),
        ("she has",     "she's"),
        ("she will",    "she'll"),
        ("she would",   "she'd"),
        ("it is",       "it's"),
        ("it has",      "it's"),
        ("it will",     "it'll"),
        ("we are",      "we're"),
        ("we have",     "we've"),
        ("we will",     "we'll"),
        ("we would",    "we'd"),
        ("they are",    "they're"),
        ("they have",   "they've"),
        ("they will",   "they'll"),
        ("they would",  "they'd"),
        ("that is",     "that's"),
        ("that has",    "that's"),
        ("that will",   "that'll"),
        ("there is",    "there's"),
        ("what is",     "what's"),
        ("what has",    "what's"),
        ("what will",   "what'll"),
        ("who is",      "who's"),
        ("who has",     "who's"),
        ("who will",    "who'll"),
        ("where is",    "where's"),
        ("when is",     "when's"),
        ("how is",      "how's"),
        ("is not",      "isn't"),
        ("are not",     "aren't"),
        ("was not",     "wasn't"),
        ("were not",    "weren't"),
        ("will not",    "won't"),
        ("would not",   "wouldn't"),
        ("can not",     "can't"),
        ("cannot",      "can't"),
        ("could not",   "couldn't"),
        ("should not",  "shouldn't"),
        ("do not",      "don't"),
        ("does not",    "doesn't"),
        ("did not",     "didn't"),
        ("has not",     "hasn't"),
        ("have not",    "haven't"),
        ("had not",     "hadn't"),
        ("must not",    "mustn't"),
        ("need not",    "needn't"),
        ("let us",      "let's"),
    ]

    // MARK: - Formal Expansions (contracted → expanded)

    static let formalExpansions: [(contracted: String, expanded: String)] = [
        ("I'm",       "I am"),
        ("I've",      "I have"),
        ("I'll",      "I will"),
        ("you're",    "you are"),
        ("you've",    "you have"),
        ("you'll",    "you will"),
        ("you'd",     "you would"),
        ("he's",      "he is"),
        ("he'll",     "he will"),
        ("he'd",      "he would"),
        ("she's",     "she is"),
        ("she'll",    "she will"),
        ("she'd",     "she would"),
        ("it's",      "it is"),
        ("it'll",     "it will"),
        ("we're",     "we are"),
        ("we've",     "we have"),
        ("we'll",     "we will"),
        ("we'd",      "we would"),
        ("they're",   "they are"),
        ("they've",   "they have"),
        ("they'll",   "they will"),
        ("they'd",    "they would"),
        ("that's",    "that is"),
        ("there's",   "there is"),
        ("what's",    "what is"),
        ("who's",     "who is"),
        ("where's",   "where is"),
        ("when's",    "when is"),
        ("how's",     "how is"),
        ("isn't",     "is not"),
        ("aren't",    "are not"),
        ("wasn't",    "was not"),
        ("weren't",   "were not"),
        ("won't",     "will not"),
        ("wouldn't",  "would not"),
        ("can't",     "cannot"),
        ("couldn't",  "could not"),
        ("shouldn't", "should not"),
        ("don't",     "do not"),
        ("doesn't",   "does not"),
        ("didn't",    "did not"),
        ("hasn't",    "has not"),
        ("haven't",   "have not"),
        ("hadn't",    "had not"),
        ("mustn't",   "must not"),
        ("needn't",   "need not"),
        ("let's",     "let us"),
    ]

    // MARK: - Past Participles (for "it's" → "it has" detection)

    static let pastParticiples: Set<String> = [
        "been", "gone", "done", "made", "taken", "given", "shown",
        "grown", "become", "come", "seen", "known", "found",
        "gotten", "broken", "chosen", "driven", "eaten", "fallen",
        "forgotten", "frozen", "hidden", "proven", "risen",
        "spoken", "stolen", "sworn", "thrown", "worn", "written",
    ]

    // MARK: - Pronouns with contractions (to distinguish from possessive 's)

    static let pronounsWithContractions: Set<String> = [
        "he", "she", "it", "that", "there", "what", "who", "where", "when", "how",
    ]

    // MARK: - Expanded App Style Map

    static let appStyleMap: [String: AppStyle] = [
        // Casual — Messaging & Social
        "com.apple.MobileSMS":              .casual,
        "com.apple.iChat":                  .casual,
        "com.tinyspeck.slackmacgap":        .casual,
        "com.slack.Slack":                  .casual,
        "com.hnc.Discord":                  .casual,
        "org.whispersystems.signal-desktop": .casual,
        "org.telegram.desktop":             .casual,
        "ru.keepcoder.Telegram":            .casual,
        "com.facebook.archon.developerID":  .casual,
        "com.beeper.Beeper":                .casual,
        "com.viber.osx":                    .casual,
        "jp.naver.line.mac":                .casual,
        "com.reddit.desktop":               .casual,

        // Formal — Email & Documents
        "com.apple.mail":                   .formal,
        "com.microsoft.Outlook":            .formal,
        "com.google.Chrome":                .formal,
        "com.apple.Safari":                 .formal,
        "com.apple.iWork.Pages":            .formal,
        "com.microsoft.Word":               .formal,
        "com.apple.Notes":                  .formal,
        "md.obsidian":                      .formal,
        "com.notion.id":                    .formal,
        "com.apple.TextEdit":               .formal,
        "com.google.docs":                  .formal,
        "com.microsoft.Excel":              .formal,
        "com.microsoft.Powerpoint":         .formal,
        "com.apple.iWork.Keynote":          .formal,
        "com.apple.iWork.Numbers":          .formal,
        "net.ia.presenter":                 .formal,
        "com.ulyssesapp.mac":               .formal,
        "com.multimarkdown.composer.mac":   .formal,

        // Code — IDE & Code Editors
        "com.apple.dt.Xcode":              .code,
        "com.microsoft.VSCode":            .code,
        "com.sublimetext.4":               .code,
        "com.sublimetext.3":               .code,
        "com.jetbrains.intellij":          .code,
        "com.jetbrains.pycharm":           .code,
        "com.jetbrains.WebStorm":          .code,
        "com.jetbrains.goland":            .code,
        "com.jetbrains.CLion":             .code,
        "com.jetbrains.rider":             .code,
        "dev.zed.Zed":                     .code,
        "com.github.atom":                 .code,
        "co.noteplan.NotePlan3":           .code,
        "com.panic.Nova":                  .code,
        "com.barebones.bbedit":            .code,
        "com.macromates.TextMate":         .code,
        "com.googlecode.iterm2":           .code,
        "com.apple.Terminal":              .code,
        "net.kovidgoyal.kitty":            .code,
        "io.alacritty":                    .code,
        "com.mitchellh.ghostty":           .code,
    ]
}
